//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Entity
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// The PrivateMessage entity model
    /// </summary>
    public partial class PrivateMessage
    {

        /// <summary>
        /// Gets or sets the private message identifier.
        /// </summary>
        /// <value>
        /// The private message identifier.
        /// </value>
        public int PrivateMessageID { get; set; }

        /// <summary>
        /// Gets or sets the message.
        /// </summary>
        /// <value>
        /// The private message.
        /// </value>
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets the author identifier.
        /// </summary>
        /// <value>
        /// The author identifier.
        /// </value>
        public int AuthorID { get; set; }

        /// <summary>
        /// Gets or sets the creation date.
        /// </summary>
        /// <value>
        /// The creation date of message.
        /// </value>
        public System.DateTime CreationDate { get; set; }

        /// <summary>
        /// Gets or sets the message title identifier.
        /// </summary>
        /// <value>
        /// The message title identifier.
        /// </value>
        public int MessageTitleID { get; set; }
    
        public virtual MessageTitle MessageTitle { get; set; }
        public virtual User User { get; set; }
    }
}
