//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Entity
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// The User entity model
    /// </summary>
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.MessageTitlesFrom = new HashSet<MessageTitle>();
            this.MessageTitlesTo = new HashSet<MessageTitle>();
            this.PrivateMessages = new HashSet<PrivateMessage>();
        }

        /// <summary>
        /// Gets or sets the user identifier.
        /// </summary>
        /// <value>
        /// The user identifier.
        /// </value>
        public int UserID { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>
        /// The user name.
        /// </value>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the login.
        /// </summary>
        /// <value>
        /// The user login.
        /// </value>
        public string Login { get; set; }

        /// <summary>
        /// Gets or sets the password.
        /// </summary>
        /// <value>
        /// The user password.
        /// </value>
        public string Password { get; set; }

        /// <summary>
        /// Gets or sets the confirm password.
        /// </summary>
        /// <value>
        /// The confirm password.
        /// </value>
        public string ConfirmPassword { get; set; }

        /// <summary>
        /// Gets or sets the downloads count.
        /// </summary>
        /// <value>
        /// The downloads count of user.
        /// </value>
        public int DownloadsCount { get; set; }

        /// <summary>
        /// Gets or sets the email.
        /// </summary>
        /// <value>
        /// The user email.
        /// </value>
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets the registration date.
        /// </summary>
        /// <value>
        /// The registration date of user.
        /// </value>
        public System.DateTime RegistrationDate { get; set; }

        /// <summary>
        /// Gets or sets the role identifier.
        /// </summary>
        /// <value>
        /// The role identifier.
        /// </value>
        public int RoleID { get; set; }

        /// <summary>
        /// Gets or sets the image.
        /// </summary>
        /// <value>
        /// The user image/avatar.
        /// </value>
        public string Image { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<MessageTitle> MessageTitlesFrom { get; set; }
        public virtual ICollection<MessageTitle> MessageTitlesTo { get; set; }
        public virtual ICollection<PrivateMessage> PrivateMessages { get; set; }
    }
}
