//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.EntityModel
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// The Comment entity model
    /// </summary>
    public partial class Comment
    {

        /// <summary>
        /// Gets or sets the comment identifier.
        /// </summary>
        /// <value>
        /// The comment identifier.
        /// </value>
        public int CommentID { get; set; }

        /// <summary>
        /// Gets or sets the author identifier.
        /// </summary>
        /// <value>
        /// The author identifier.
        /// </value>
        public int AuthorID { get; set; }

        /// <summary>
        /// Gets or sets the torrent identifier.
        /// </summary>
        /// <value>
        /// The torrent identifier.
        /// </value>
        public int TorrentID { get; set; }

        /// <summary>
        /// Gets or sets the message.
        /// </summary>
        /// <value>
        /// The comment message.
        /// </value>
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets the posted date.
        /// </summary>
        /// <value>
        /// The posted date of comment.
        /// </value>
        public System.DateTime PostedDate { get; set; }

        /// <summary>
        /// Gets or sets the last edit of comment.
        /// </summary>
        /// <value>
        /// The last edit.
        /// </value>
        public Nullable<System.DateTime> LastEdit { get; set; }
    
        public virtual Torrent Torrent { get; set; }
        public virtual User User { get; set; }
    }
}
