//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.EntityModel
{
    using System;
    using System.Collections.Generic;


    /// <summary>
    /// The Role entity model
    /// </summary>
    public partial class Role
    {
        public Role()
        {
            this.Users = new HashSet<User>();
        }

        /// <summary>
        /// Gets or sets the role identifier.
        /// </summary>
        /// <value>
        /// The role identifier.
        /// </value>
        public int RoleID { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>
        /// The role name.
        /// </value>
        public string Name { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
