//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.EntityModel
{
    using System;
    using System.Collections.Generic;


    /// <summary>
    /// The TorrentType entity model
    /// </summary>
    public partial class TorrentType
    {
        public TorrentType()
        {
            this.Torrents = new HashSet<Torrent>();
        }

        /// <summary>
        /// Gets or sets the torrent type identifier.
        /// </summary>
        /// <value>
        /// The torrent type identifier.
        /// </value>
        public int TorrentTypeID { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>
        /// The type name.
        /// </value>
        public string Name { get; set; }
    
        public virtual ICollection<Torrent> Torrents { get; set; }
    }
}
