//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.EntityModel
{
    using System;
    using System.Collections.Generic;


    /// <summary>
    /// The Torrent entity model
    /// </summary>
    public partial class Torrent
    {
        public Torrent()
        {
            this.TorrentCharacteristics = new HashSet<TorrentCharacteristic>();
            this.Comments = new HashSet<Comment>();
        }

        /// <summary>
        /// Gets or sets the torrent identifier.
        /// </summary>
        /// <value>
        /// The torrent identifier.
        /// </value>
        public int TorrentID { get; set; }

        /// <summary>
        /// Gets or sets the torrent type identifier.
        /// </summary>
        /// <value>
        /// The torrent type identifier.
        /// </value>
        public int TorrentTypeID { get; set; }

        /// <summary>
        /// Gets or sets the torrent file identifier.
        /// </summary>
        /// <value>
        /// The torrent file identifier.
        /// </value>
        public int TorrentFileID { get; set; }
    
        public virtual TorrentType TorrentType { get; set; }
        public virtual ICollection<TorrentCharacteristic> TorrentCharacteristics { get; set; }
        public virtual TorrentFile TorrentFile { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
