//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.EntityModel
{
    using System;
    using System.Collections.Generic;


    /// <summary>
    /// The TorrentCharacteristic entity model
    /// </summary>
    public partial class TorrentCharacteristic
    {

        /// <summary>
        /// Gets or sets the torrent characteristic identifier.
        /// </summary>
        /// <value>
        /// The torrent characteristic identifier.
        /// </value>
        public int TorrentCharacteristicID { get; set; }

        /// <summary>
        /// Gets or sets the torrent identifier.
        /// </summary>
        /// <value>
        /// The torrent identifier.
        /// </value>
        public int TorrentID { get; set; }

        /// <summary>
        /// Gets or sets the characteristic identifier.
        /// </summary>
        /// <value>
        /// The characteristic identifier.
        /// </value>
        public int CharacteristicID { get; set; }

        /// <summary>
        /// Gets or sets the characteristic value.
        /// </summary>
        /// <value>
        /// The characteristic value of torrent.
        /// </value>
        public string CharacteristicValue { get; set; }
    
        public virtual Characteristic Characteristic { get; set; }
        public virtual Torrent Torrent { get; set; }
    }
}
